### ISSUE TITLE
panic: Your test failed

### ISSUE THREAD

**Issue by wangping710** [cloudfoundry/hm9000#10]
I git clone the latest code, then run the test case error
--- export GOPATH=$HOME/hm-workspace
--- export PATH=$HOME/hm-workspace/bin:$PATH
--- gem install eventmachine -v 0.12.10
--- gem install thin -v 1.4.1
-- gem install nats -v 0.4.28
--- export PATH=$HOME/bin/zookeeper/bin:$HOME/hm-workspace/bin:$PATH
---root@wangping-vm02:~/hm-workspace/src/github.com/cloudfoundry/hm9000# ginkgo -r  --randomizeAllSpecs --failOnPending --skipMeasurements
[1413482271] Metricsaccountant Suite - 12/12 specs ?⑩?⑩?⑩?⑩?⑩?⑩?⑩?⑩?⑩?⑩?⑩??SUCCESS! 2.43233ms PASS
--- FAIL: TestHM9000 (0.00 seconds)
panic: 
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

	defer GinkgoRecover()

at the top of the goroutine that caused this panic.
 [recovered]
	panic: 
Your test failed.
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.

But, if you make an assertion in a goroutine, Ginkgo can't capture the panic.
To circumvent this, you should call

	defer GinkgoRecover()

at the top of the goroutine that caused this panic.

goroutine 22 [running]:
runtime.panic(0x6d0720, 0xc208000ae0)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
testing.func路006()
	/usr/local/go/src/pkg/testing/testing.go:416 +0x176
runtime.panic(0x6d0720, 0xc208000ae0)
	/usr/local/go/src/pkg/runtime/panic.c:248 +0x18d
github.com/onsi/ginkgo.Fail(0xc208003e60, 0x116, 0xc2080010b0, 0x1, 0x1)
	/root/hm-workspace/src/github.com/onsi/ginkgo/ginkgo_dsl.go:229 +0xeb
github.com/onsi/gomega/internal/assertion.(*Assertion).match(0xc208042c00, 0x7f58fb796848, 0x9db760, 0x0, 0xc208000e20, 0x1, 0x1, 0x7f58fb60bda8)
	/root/hm-workspace/src/github.com/onsi/gomega/internal/assertion/assertion.go:69 +0x324
github.com/onsi/gomega/internal/assertion.(*Assertion).ShouldNot(0xc208042c00, 0x7f58fb796848, 0x9db760, 0xc208000e20, 0x1, 0x1, 0xc208042c00)
	/root/hm-workspace/src/github.com/onsi/gomega/internal/assertion/assertion.go:31 +0x9a
github.com/cloudfoundry/storeadapter/storerunner/etcdstorerunner.(*ETCDClusterRunner).start(0xc2080425c0, 0x1)
	/root/hm-workspace/src/github.com/cloudfoundry/storeadapter/storerunner/etcdstorerunner/etcd_cluster_runner.go:142 +0xa7d
github.com/cloudfoundry/storeadapter/storerunner/etcdstorerunner.(*ETCDClusterRunner).Start(0xc2080425c0)
	/root/hm-workspace/src/github.com/cloudfoundry/storeadapter/storerunner/etcdstorerunner/etcd_cluster_runner.go:40 +0x2c
github.com/cloudfoundry/hm9000/hm_test.TestHM9000(0xc20804e1b0)
	/root/hm-workspace/src/github.com/cloudfoundry/hm9000/hm/hm_suite_test.go:18 +0xbd
testing.tRunner(0xc20804e1b0, 0x9d00a0)
	/usr/local/go/src/pkg/testing/testing.go:422 +0x8b
created by testing.RunTests
	/usr/local/go/src/pkg/testing/testing.go:504 +0x8db

goroutine 16 [chan receive]:
testing.RunTests(0x88bd88, 0x9d00a0, 0x1, 0x1, 0x88bc01)
	/usr/local/go/src/pkg/testing/testing.go:505 +0x923
testing.Main(0x88bd88, 0x9d00a0, 0x1, 0x1, 0x9e04e0, 0x0, 0x0, 0x9e04e0, 0x0, 0x0)
	/usr/local/go/src/pkg/testing/testing.go:435 +0x84
main.main()
	github.com/cloudfoundry/hm9000/hm/_test/_testmain.go:47 +0x9c

goroutine 19 [finalizer wait]:
runtime.park(0x413440, 0x9dac30, 0x9d8e69)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x9dac30, 0x9d8e69)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
	/usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init路1
	/usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

Ginkgo ran 9 suites in 19.537042993s
Test Suite Failed

my go version: go version go1.3.3 linux/amd64

What's the problem?

**Comment by Amit-PivotalLabs** [comment]
Closing due to inactivity.
